name: Terraform DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]
  schedule:
    - cron: '0 9 * * 1'  # Weekly drift detection - Monday 9 AM UTC
  workflow_dispatch:  # Manual trigger

env:
  TF_WORKING_DIR: .
  TF_VERSION: 1.6.0
  AWS_REGION: us-east-1

# Prevent concurrent runs
concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  security-scan:
    name: Security & Compliance Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      security-events: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run Checkov Security Scan
        uses: bridgecrewio/checkov-action@3b2536c6ba1b6e35e5a84ec67a6f2f1c73715e5c # v12.2813.0
        with:
          directory: ${{ env.TF_WORKING_DIR }}
          framework: terraform
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true
          download_external_modules: true

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: checkov-results.sarif
          category: checkov

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@19a52fbac37dacb22a09518e4ef6ee234f2d4987 # v4.0.0
        with:
          tflint_version: latest

      - name: Initialize TFLint
        run: tflint --init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Run TFLint
        run: tflint -f compact --force
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Run Trivy IaC Scanner
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # 0.24.0
        with:
          scan-type: 'config'
          scan-ref: ${{ env.TF_WORKING_DIR }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
          category: trivy

      - name: Run tfsec Security Scanner
        uses: aquasecurity/tfsec-action@b466648d6e39e7c75324f25d83891162a721f2d6 # v1.0.3
        with:
          working_directory: ${{ env.TF_WORKING_DIR }}
          format: sarif
          soft_fail: true

      - name: Upload tfsec SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: tfsec.sarif
          category: tfsec

      - name: Terrascan IaC Scanner
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_dir: ${{ env.TF_WORKING_DIR }}
          sarif_upload: true
        continue-on-error: true

      - name: Check for Remote State Backend
        run: |
          echo "🔍 Verifying remote state configuration..."
          if grep -rq "backend.*\"s3\"" ${{ env.TF_WORKING_DIR }}/*.tf; then
            echo "✅ S3 backend detected"
          elif grep -rq "backend.*\"remote\"" ${{ env.TF_WORKING_DIR }}/*.tf; then
            echo "✅ Remote backend detected"
          else
            echo "⚠️ WARNING: No remote backend detected. State should be stored remotely!"
            exit 1
          fi

  terraform-validate:
    name: Terraform Validation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: security-scan
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        id: fmt
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -backend=false -input=false

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate -no-color

      - name: Generate Terraform Docs
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          working-dir: ${{ env.TF_WORKING_DIR }}
          output-file: TERRAFORM_DOCS.md
          output-method: inject
          fail-on-diff: false

      - name: Validation Results Comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            
            <details><summary>Validation Output</summary>
            
            \`\`\`
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: terraform-validate
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -input=false

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=${{ env.TF_WORKING_DIR }} plan -no-color -input=false -out=tfplan 2>&1 | tee plan_output.txt
          echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Save Plan Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          retention-days: 30

      - name: Save Plan Output
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: terraform-plan-output
          path: plan_output.txt
          retention-days: 30

      - name: Setup Infracost
        uses: infracost/actions/setup@1e2cacf774c8d87f43c88dc97e9e5f81d6d1c85c # v3.0.0
        if: github.event_name == 'pull_request'
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        if: github.event_name == 'pull_request'
        run: |
          infracost breakdown --path=${{ env.TF_WORKING_DIR }}/tfplan \
            --format=json \
            --out-file=/tmp/infracost.json
        continue-on-error: true

      - name: Post Infracost Comment
        if: github.event_name == 'pull_request'
        run: |
          infracost comment github --path=/tmp/infracost.json \
            --repo=$GITHUB_REPOSITORY \
            --github-token=${{ secrets.GITHUB_TOKEN }} \
            --pull-request=${{ github.event.pull_request.number }} \
            --behavior=update
        continue-on-error: true

      - name: Comment Plan on PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('plan_output.txt', 'utf8');
            const truncatedPlan = planOutput.length > 65000 ? 
              planOutput.substring(0, 65000) + '\n\n... (truncated)' : 
              planOutput;
            
            const output = `#### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`terraform
            ${truncatedPlan}
            \`\`\`
            
            </details>
            
            **Plan Exit Code:** ${{ steps.plan.outputs.exitcode }}
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Check Plan Status
        if: steps.plan.outputs.exitcode != 0
        run: exit 1

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    timeout-minutes: 45
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://console.aws.amazon.com
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Apply

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -input=false

      - name: Download Plan Artifact
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        run: |
          terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve -input=false tfplan
        
      - name: Generate SBOM
        run: |
          echo "# Terraform Infrastructure SBOM" > TERRAFORM_SBOM.md
          echo "**Generated:** $(date)" >> TERRAFORM_SBOM.md
          echo "" >> TERRAFORM_SBOM.md
          terraform -chdir=${{ env.TF_WORKING_DIR }} state list >> TERRAFORM_SBOM.md

      - name: Save SBOM Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: terraform-sbom
          path: TERRAFORM_SBOM.md
          retention-days: 90

  drift-detection:
    name: Drift Detection
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.event_name == 'schedule'
    permissions:
      contents: read
      id-token: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform-Drift

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -input=false

      - name: Terraform Plan - Drift Check
        id: drift
        run: |
          terraform -chdir=${{ env.TF_WORKING_DIR }} plan -detailed-exitcode -no-color -input=false > drift_output.txt 2>&1
          echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Create Drift Issue
        if: steps.drift.outputs.exitcode == 2
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const fs = require('fs');
            const driftOutput = fs.readFileSync('drift_output.txt', 'utf8');
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Infrastructure Drift Detected',
              body: `## Drift Detection Report
              
              **Date:** ${new Date().toISOString()}
              **Branch:** main
              
              Infrastructure drift has been detected. The actual state differs from the desired state defined in Terraform.
              
              <details><summary>Drift Details</summary>
              
              \`\`\`terraform
              ${driftOutput.substring(0, 65000)}
              \`\`\`
              
              </details>
              
              ### Recommended Actions
              1. Review the changes above
              2. Determine if changes were made outside Terraform
              3. Either update Terraform code or revert manual changes
              4. Run terraform apply to reconcile
              
              **Labels:** infrastructure, drift, terraform`,
              labels: ['infrastructure', 'drift', 'terraform', 'priority-high']
            });

      - name: Notify on Success
        if: steps.drift.outputs.exitcode == 0
        run: echo "✅ No drift detected - infrastructure matches desired state"

  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [security-scan, terraform-validate, terraform-plan, terraform-apply]
    if: failure()
    permissions:
      contents: read
    
    steps:
      - name: Notify Failure
        run: |
          echo "❌ Workflow failed. Check the logs for details."
          echo "Configure Slack/Teams/Email notifications here"
          # Add your notification logic here
          # Example: Slack webhook, Teams webhook, or email action
