name: Deploy Static Site

on:
  push:
    branches: [ "main" ]
    paths:
      - "site/**"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # OR use access keys instead:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Sync site to S3
        run: aws s3 sync site/ s3://${{ vars.SITE_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront cache
        run: |
          DIST_ID=$(aws cloudfront list-distributions \
            --query "DistributionList.Items[?DomainName=='${{ vars.CLOUDFRONT_DOMAIN }}'].Id | [0]" \
            --output text)
          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"

